# gVV build entry point. Two readable application scripts share five core modules.
# CUDA/ROOT locations and build directories may be overridden by the caller.
PROJECT_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
BUILD_DIR ?= $(PROJECT_ROOT)/build
OBJ_DIR ?= $(BUILD_DIR)/obj
BIN_DIR ?= $(PROJECT_ROOT)/bin
TEST_BIN_DIR ?= $(BUILD_DIR)/tests

# Reproducible default toolchain used on the IHEP AlmaLinux GPU nodes.
GVV_CUDA_ROOT ?= /usr/local/cuda-12
ROOT_PREFIX ?= /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.32.02/x86_64-almalinux9.4-gcc114-opt
NVCC ?= $(GVV_CUDA_ROOT)/bin/nvcc

ROOT_LIBS = -L$(ROOT_PREFIX)/lib -lCore -lRIO -lNet -lHist -lGraf \
	-lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics \
	-lMathCore -lThread -lm -ldl -m64 -lRooFitCore -lRooFit -lrt \
	-lMinuit -lFoam -lMathMore
ROOT_INCLUDES = -I$(ROOT_PREFIX)/include
PROJECT_INCLUDES = -I$(PROJECT_ROOT)
RPATH = -Xlinker -rpath -Xlinker $(ROOT_PREFIX)/lib
CUDA_ARCH = -gencode arch=compute_70,code=sm_70 \
	-gencode arch=compute_80,code=sm_80
COMPILE_FLAGS = -O2 -g -std=c++17 $(CUDA_ARCH)
DEPENDENCY_FLAGS = -MMD -MP

# Object paths mirror source paths. Header dependencies are generated by nvcc.
CORE_SOURCES = core/ModelIO.cpp core/Model.cu core/Minuit.cpp core/IO.cpp \
    core/Sample.cu core/Amplitude.cu core/AmplitudeKernels.cu core/Projection.cu \
    core/physics/Waves.cu core/physics/OmegaWidth.cu
CORE_OBJECTS = $(addprefix $(OBJ_DIR)/,$(addsuffix .o,$(basename $(CORE_SOURCES))))
FIT_OBJECT = $(OBJ_DIR)/fit/Fit.o
POST_OBJECT = $(OBJ_DIR)/post/Post.o
ALL_OBJECTS = $(CORE_OBJECTS) $(FIT_OBJECT) $(POST_OBJECT)

TESTS = \
	$(TEST_BIN_DIR)/test_omega_resolution.exe \
	$(TEST_BIN_DIR)/test_omega_resolution_model.exe \
	$(TEST_BIN_DIR)/test_dynamics.exe \
	$(TEST_BIN_DIR)/test_gvv_amplitude.exe \
	$(TEST_BIN_DIR)/test_propagator_registry.exe \
	$(TEST_BIN_DIR)/test_propagator_compiler.exe \
	$(TEST_BIN_DIR)/test_fit_parameters.exe \
	$(TEST_BIN_DIR)/test_fit_config.exe \
	$(TEST_BIN_DIR)/test_fit_output.exe \
	$(TEST_BIN_DIR)/test_fit_state.exe \
	$(TEST_BIN_DIR)/test_gvv_model_signature.exe \
	$(TEST_BIN_DIR)/test_fit_engine.exe \
	$(TEST_BIN_DIR)/test_model.exe \
	$(TEST_BIN_DIR)/test_wave_registry.exe \
	$(TEST_BIN_DIR)/test_likelihood.exe
GPU_TESTS = \
	$(TEST_BIN_DIR)/test_omega_resolution_gpu.exe \
	$(TEST_BIN_DIR)/test_tensor_building_blocks.exe \
	$(TEST_BIN_DIR)/test_gvv_wave_numerics.exe \
	$(TEST_BIN_DIR)/test_intensity_equivalence.exe

DEPENDENCY_FILES = $(ALL_OBJECTS:.o=.d) $(TESTS:.exe=.d) $(GPU_TESTS:.exe=.d)
.PHONY: all fit post tests check gpu-tests check-gpu clean
all: fit
fit: $(BIN_DIR)/Fit.exe
post: $(BIN_DIR)/Post.exe
tests: $(TESTS)
gpu-tests: $(GPU_TESTS)

$(OBJ_DIR)/%.o: %.cu
	@mkdir -p $(dir $@)
	$(NVCC) $(ROOT_INCLUDES) $(PROJECT_INCLUDES) $(COMPILE_FLAGS) $(DEPENDENCY_FLAGS) -c $< -o $@

$(OBJ_DIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(NVCC) $(ROOT_INCLUDES) $(PROJECT_INCLUDES) $(COMPILE_FLAGS) $(DEPENDENCY_FLAGS) -x cu -c $< -o $@

$(BIN_DIR)/Fit.exe: $(CORE_OBJECTS) $(FIT_OBJECT)
	@mkdir -p $(dir $@)
	$(NVCC) $^ $(ROOT_LIBS) $(RPATH) $(COMPILE_FLAGS) -o $@

$(BIN_DIR)/Post.exe: $(CORE_OBJECTS) $(POST_OBJECT)
	@mkdir -p $(dir $@)
	$(NVCC) $^ $(ROOT_LIBS) $(RPATH) $(COMPILE_FLAGS) -o $@

# Script-local policy is tested by including its source with main disabled;
# it does not need a production Fit.h or a second copy of the algorithm.
$(TEST_BIN_DIR)/%.exe: tests/%.cu $(CORE_OBJECTS)
	@mkdir -p $(dir $@)
	$(NVCC) $< $(CORE_OBJECTS) $(ROOT_LIBS) $(RPATH) $(ROOT_INCLUDES) $(PROJECT_INCLUDES) $(COMPILE_FLAGS) $(DEPENDENCY_FLAGS) -o $@

$(TEST_BIN_DIR)/%.o: tests/%.cpp
	@mkdir -p $(dir $@)
	$(NVCC) $(ROOT_INCLUDES) $(PROJECT_INCLUDES) $(COMPILE_FLAGS) $(DEPENDENCY_FLAGS) -x cu -c $< -o $@

$(TEST_BIN_DIR)/%.exe: $(TEST_BIN_DIR)/%.o $(CORE_OBJECTS)
	$(NVCC) $(TEST_BIN_DIR)/$*.o $(CORE_OBJECTS) $(ROOT_LIBS) $(RPATH) $(COMPILE_FLAGS) -o $@

# Link explicit objects: older .d files may still attach source/header prerequisites
# to the executable during the first build after migration.
# Keep C++ test objects for correct incremental header dependencies.
.SECONDARY:

# Host checks do not evaluate CUDA kernels or require a GPU allocation.
check: tests
	@for test in $(TESTS); do $$test || exit $$?; done

# Run only inside an allocated GPU job; never implicitly from `make check`.
check-gpu: gpu-tests
	@for test in $(GPU_TESTS); do $$test || exit $$?; done

clean:
	rm -f $(ALL_OBJECTS) $(BIN_DIR)/Fit.exe $(BIN_DIR)/Post.exe \
	    $(TESTS) $(GPU_TESTS) $(DEPENDENCY_FILES) $(TESTS:.exe=.o)

-include $(DEPENDENCY_FILES)
